spring.jpa:
  database: mysql
  hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  hibernate.ddl-auto: update
  show-sql: true

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

spring.devtools:
  livereload:
    enabled: true
  restart:
    enabled: true

spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:mysql://localhost:3306/myapp?serverTimezone=Asia/Seoul
#  url: jdbc:mysql://jsoft.iptime.org:3306/myapp?serverTimezone=Asia/Seoul
  username: myapp
  password: 334831
  driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret-key: phj-security-with-jwt-study-secret-key
  token-expired-time-ms: 6000000
